/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://ipmaia-winterjam.pt', // Your production URL
  generateRobotsTxt: true, // (optional)
  sitemapSize: 5000, // Increase limit to keep everything in one file
  robotsTxtOptions: {
    additionalSitemaps: [
      'https://ipmaia-winterjam.pt/sitemap.xml',
    ],
    additionalRobotsTxt: `
robots.txt generated by www.seoptimer.com
User-agent: *
Disallow: /
Crawl-delay: 120

User-agent: Googlebot
Disallow: 

User-agent: googlebot-image
Disallow: 

User-agent: googlebot-mobile
Disallow: 

User-agent: Bingbot
Disallow: 

User-agent: DuckDuckBot
Disallow: 

User-agent: Baiduspider
Disallow: 

User-agent: YandexBot
Disallow: 

User-agent: Applebot
Disallow: 

User-agent: ia_archiver
Disallow: 

User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: anthropic-ai
Disallow: /

User-agent: Claude-Web
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: PerplexityBot
Disallow: /

User-agent: Omgilibot
Disallow: /

User-agent: facebookexternalhit
Disallow: /

User-agent: FacebookBot
Disallow: /

User-agent: Twitterbot
Disallow: /

User-agent: LinkedInBot
Disallow: /

User-agent: Slackbot
Disallow: /

User-agent: WhatsApp
Disallow: /

User-agent: msnbot
Disallow: /

User-agent: Slurp
Disallow: /

User-agent: Teoma
Disallow: /

User-agent: Gigabot
Disallow: /

User-agent: Robozilla
Disallow: /

User-agent: Nutch
Disallow: /

User-agent: naverbot
Disallow: /

User-agent: yeti
Disallow: /

User-agent: yahoo-mmcrawler
Disallow: /

User-agent: psbot
Disallow: /

User-agent: yahoo-blogs/v3.9
Disallow: /

Sitemap: https://ipmaia-winterjam.pt/sitemap.xml
    `,
  },
}