# IPMAIA WinterJam - Debug Stack for Portainer
# 🚀 This version has more verbose logging and simpler health checks

version: '3.8'

services:
  # PostgreSQL Database - Start Simple
  postgres:
    image: postgres:15-alpine
    container_name: winterjam-postgres-debug
    environment:
      POSTGRES_DB: winterjam_db
      POSTGRES_USER: winterjam  
      POSTGRES_PASSWORD: winterjam_secure_password_2025
    volumes:
      - postgres_data_debug:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    # Simplified health check
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "winterjam", "-d", "winterjam_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API & Admin Dashboard  
  backend:
    image: ghcr.io/syl3n7/ipmaia-winterjam-backend:latest
    container_name: winterjam-backend-debug
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_NAME: winterjam_db
      DB_USER: winterjam
      DB_PASSWORD: winterjam_secure_password_2025
      DB_PORT: 5432
      SESSION_SECRET: winterjam-super-secret-key-2025-change-me
      FRONTEND_URL: http://192.168.1.69:3000
      AUTO_MIGRATE: "true"
      AUTO_SEED: "true"
      # Debug logging
      DEBUG: "*"
    volumes:
      - backend_uploads_debug:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped
    # No health check - let's see if this helps
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 60s

  # Frontend (Next.js Website)
  frontend:
    image: ghcr.io/syl3n7/ipmaia-winterjam:latest  
    container_name: winterjam-frontend-debug
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_API_URL: http://192.168.1.69:3001/api
    depends_on:
      - backend
    restart: unless-stopped
    # No health check - let's see if this helps
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

volumes:
  postgres_data_debug:
    driver: local
  backend_uploads_debug:
    driver: local