# IPMAIA WinterJam - Portainer Stack (Local Build Version)
# Use this version if you want to build the image locally first

version: '3.8'

services:
  winterjam:
    image: ipmaia-winterjam:latest
    container_name: ipmaia-winterjam
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Watchtower for auto-updates (optional - only if using registry)
  # watchtower:
  #   image: containrrr/watchtower:latest
  #   container_name: watchtower-winterjam
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=300
  #     - WATCHTOWER_INCLUDE_STOPPED=true
  #     - WATCHTOWER_REVIVE_STOPPED=false
  #     - WATCHTOWER_LABEL_ENABLE=true
  #     - WATCHTOWER_DEBUG=true
  #   restart: unless-stopped
  #   depends_on:
  #     - winterjam

networks:
  default:
    driver: bridge