name = "gamejams-ipmaia"
main = "worker.js"
compatibility_date = "2025-09-05"

[site]
bucket = "./out"

[[routes]]
pattern = "ipmaia-winterjam.pt/*"
zone_name = "ipmaia-winterjam.pt"

[env.production]
name = "gamejams-ipmaia"
