name: HomeLab Deployment

# Add permissions to the workflow
permissions:
  contents: read  # Allow read access to the repository contents
  deployments: write  # Allow writing to deployments (if needed)
  actions: write  # Allow writing to GitHub Actions (if needed)

on:
  workflow_dispatch:  # Allow manual triggering of the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Use a self-hosted runner
    environment: deployment  # Specify the deployment environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set the Node.js version

      - name: Install dependencies
        run: npm ci  # Install dependencies using `npm ci`

      - name: Build Next.js app
        run: npm run build  # Build the Next.js application

      - name: Update PM2 to latest version
        run: |
          echo "Updating PM2 to latest version to fix security vulnerability"
          npm install -g pm2@latest
          pm2 --version

      - name: Deploy with PM2
        run: |
          git pull  # Pull the latest changes
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 is not installed"
            exit 1
          fi
          npm ci  # Reinstall dependencies (optional, if needed)
          npm run build  # Rebuild the application (optional, if needed)
          pm2 restart ecosystem.config.js  # Restart the PM2 process
